packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@prisma/engines": true
  "@scarf/scarf": false
  esbuild: true
  prisma: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - "@turbo/darwin-64@2.10.13"
  - "@turbo/darwin-arm64@2.10.13"
  - "@turbo/linux-64@2.10.13"
  - "@turbo/linux-arm64@2.10.13"
  - "@turbo/windows-64@2.10.13"
  - "@turbo/windows-arm64@2.10.13"
  - turbo@2.10.13

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@swc/core"
  - "sharp"
